### ISSUE TITLE
Starter Pack

### ISSUE THREAD

**Issue by vanishdevs** [overextended/awesome-ox#7]
A simple starter pack system (can only be done once for a character) for players to walk up to a ped and receive pre-defined items within the config. Bridge is there to support ox_core and other frameworks. Let me know if there are any issues with it.

https://github.com/vanishdevs/vanish_starterpack

**Comment by CeebDev** [comment]
You should spawn the ped etc only if you are close using for example lib.point

No need to have the ped running a animation at LS Airport if you are at Paleto

**Comment by vanishdevs** [comment]
> You should spawn the ped etc only if you are close using for example lib.point
> 
> No need to have the ped running a animation at LS Airport if you are at Paleto

Note taken, didn't even think of an implementation like this. Will update it tomorrow with new optimized logic as suggested. Thanks :)

**Comment by thelindat** [comment]
Seems a bit simple, but I guess could be considered a dev tool / showcase?

**Comment by vanishdevs** [comment]
> Seems a bit simple, but I guess could be considered a dev tool / showcase?

Yeah, it wasn't meant to be anything crazy; just a simple implementation of an ox_core bridge. I hope to contribute with a couple more complex resources in the near future.

**Comment by vanishdevs** [comment]
Do you want me to pr?

**Comment by LukeWasTakenn** [comment]
> Do you want me to pr?

Sure
